spring.application.name=api-dentalFlow-soap

spring.datasource.url=jdbc:mysql://localhost:3306/dentalflow_db
spring.datasource.username=root
spring.datasource.password=mysql

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:sYKT9thgt8iWZkClLEXrDmcpUg30iv5TOJt8zAixhYuKZO9oeHQB+fu/mO3WDJPAnv1jFmzkkqM0AeDSheOnsA==}
jwt.expiration=86400000